version: "3.8"

services:

  coupon-app-docker-compose:
    build:
      context: .
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - redis-master

  redis-master:
    image: 'bitnami/redis:latest'
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3